name: test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Prepare local xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with: 
          xmake-version: branch@master
      - name: Setup C++
        run: |
          apt update
          apt install build-essential -y
      - name: test
        run: xmake build -v -y